# -*- coding: utf-8 -*-
"""Study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRMMBjGMWzJG-OHsgPX9znANf1gEEuZS

# Prediction using Supervised ML
# TASK-1
Predict the percentage of an student based on the no. of study hours.
 
 DONE BY:
  
     UTHARA PRINCE

Importing the libraries and reading the data
"""

import pandas as pd
import numpy as np

data=pd.read_csv("http://bit.ly""/w-data")
data

Y_train=data.drop(["Hours"],axis=1)
Y_train

data=data.drop(["Scores"],axis=1)
data

"""Spliting into Training and Testing data"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,Y_train,test_size=0.2,random_state=0)
x_train.shape

from sklearn import metrics
def error(x_test,y_test,model_name):
  predict=model_name.predict(x_test)
  print("MAE",metrics.mean_absolute_error(y_test,predict))
  print("MSE",metrics.mean_squared_error(y_test,predict))
  print("RMSE",np.sqrt(metrics.mean_squared_error(y_test,predict)))

"""Training the model"""

from sklearn import linear_model
linear_reg=linear_model.LinearRegression()
linear_reg.fit(x_train,y_train) 
error(x_test,y_test,linear_reg)
Acc=linear_reg.score(x_test,y_test)
print(Acc*100,"%")

data=[9.25]
prediction=linear_reg.predict([data])
prediction
print("The marks for a person studying for 9.25hrs is {}".format(prediction[0]))